name: "CI"

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Connect to container registry (dockerhub)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag and push image
      id: build
      run: |
        # Build a docker container and push it to CR
        docker pull nginx
        docker tag nginx docker.io/shabbirsaifee/nginx:${GITHUB_REF##*/
        
        echo "Pushing image to CR..."
        
        docker push docker.io/shabbirsaifee/nginx:${GITHUB_REF##*/}
        echo "::set-output name=IMAGE_TAG::${GITHUB_REF##*/}"
        echo "::set-output name=image::docker.io/shabbirsaifee/nginx:${GITHUB_REF##*/}"
